# Generated by Django 4.2.23 on 2025-07-20 08:37

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=72, verbose_name="عنوان")),
                (
                    "logo",
                    models.ImageField(
                        upload_to=brand.models.brand_logo_file_path, verbose_name="لوگو"
                    ),
                ),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
    ]
