# Generated by Django 4.2.23 on 2025-07-20 07:04

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=gallery.models.gallery_image_file_path,
                        verbose_name="تصویر",
                    ),
                ),
            ],
            options={
                "verbose_name": "گالری",
                "verbose_name_plural": "گالری",
            },
        ),
    ]
