# Generated by Django 4.2.23 on 2025-07-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=25, verbose_name="کد")),
                ("percentage", models.IntegerField(default=0, verbose_name="درصد")),
                ("start_date", models.DateField(verbose_name="زمان شروع")),
                ("end_date", models.DateField(verbose_name="زمان انقضاء")),
                (
                    "count",
                    models.IntegerField(default=0, verbose_name="تعداد قابل مصرف"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="علت تخفیف"
                    ),
                ),
            ],
            options={
                "verbose_name": "تخفیف",
                "verbose_name_plural": "تخفیفات",
            },
        ),
    ]
