# Generated by Django 4.2.23 on 2025-07-20 07:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gallery", "0001_initial"),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("order", models.IntegerField(default=0, verbose_name="الویت نمایش")),
                ("image_alt", models.CharField(blank=True, max_length=72, null=True)),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blog_categories",
                        to="gallery.gallery",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="blog.blogcategory",
                        verbose_name="زیردسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته بندی",
                "verbose_name_plural": "دسته های مقاله",
            },
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=85, verbose_name="عنوان")),
                ("slug", models.SlugField(max_length=170, verbose_name="اسلاگ")),
                (
                    "short_desc",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="توضیحات کوتاه",
                    ),
                ),
                (
                    "desc",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="توضیحات"
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=72, null=True)),
                (
                    "image_title",
                    models.CharField(blank=True, max_length=125, null=True),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="زمان انتشار",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogs",
                        to="blog.blogcategory",
                        verbose_name="دسته",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="blogs",
                        to="gallery.gallery",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="برچسب ها",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات",
            },
        ),
    ]
