# Generated by Django 4.2.23 on 2025-07-20 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("province", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=225, verbose_name="نام کامل"),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="توضیحات"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="خیابان"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="کد پستی"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="province.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="province.province",
                        verbose_name="استان",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشانی",
                "verbose_name_plural": "نشانی ها",
            },
        ),
    ]
