# Generated by Django 4.2.23 on 2025-07-20 08:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="متن"
                    ),
                ),
            ],
            options={
                "verbose_name": "درباره ما",
                "verbose_name_plural": "درباره ما",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="عنوان")),
                (
                    "text",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="متن"
                    ),
                ),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "تماس با ما",
            },
        ),
        migrations.CreateModel(
            name="EmailAndPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email1",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="پست الکترونیک اول",
                    ),
                ),
                (
                    "email2",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="پست الکترونیک دوم",
                    ),
                ),
                (
                    "phone1",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        verbose_name="شماره تماس اول",
                    ),
                ),
                (
                    "phone2",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        verbose_name="شماره تماس دوم",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشانی",
                "verbose_name_plural": "نشانی ها",
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125, verbose_name="دسته بندی")),
            ],
            options={
                "verbose_name": "دسته سوالات",
                "verbose_name_plural": "دسته های سوالات",
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="تیتر"
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="پاراگراف"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
            ],
            options={
                "verbose_name": "فوتر",
                "verbose_name_plural": "فوتر",
            },
        ),
        migrations.CreateModel(
            name="HomeHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                        verbose_name="لینک تیتر",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="سر تیتر"
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="توضیح تیتر"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="وضعیت")),
            ],
            options={
                "verbose_name": "تیتر صفحه اصلی",
                "verbose_name_plural": "تیتر صفحه اصلی",
            },
        ),
        migrations.CreateModel(
            name="SliderAndBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="تیتر"
                    ),
                ),
                (
                    "paragraph",
                    models.CharField(
                        blank=True, max_length=125, null=True, verbose_name="پاراگراف"
                    ),
                ),
                (
                    "link_text",
                    models.CharField(
                        blank=True, max_length=72, null=True, verbose_name="متن لینک"
                    ),
                ),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        error_messages={"invalid": "مقدار وارد شده صحیح نم باشد"},
                        max_length=250,
                        null=True,
                        verbose_name="آدرس لینک",
                    ),
                ),
                (
                    "is_slider",
                    models.BooleanField(
                        default=False, verbose_name="آیا اسلایدر هست ؟"
                    ),
                ),
            ],
            options={
                "verbose_name": "اسلایدر و بنر",
                "verbose_name_plural": "اسلایدر و بنرها",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=125, verbose_name="نام کامل"),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="موبایل")),
                ("text", models.CharField(max_length=500, verbose_name="متن")),
                (
                    "create_data",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ارسال"),
                ),
            ],
            options={
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت ها",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500, verbose_name="سوال")),
                ("answer", ckeditor.fields.RichTextField(verbose_name="جواب")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="siteinfo.faqcategory",
                        verbose_name="دسته",
                    ),
                ),
            ],
            options={
                "verbose_name": "سوال",
                "verbose_name_plural": "سوالات",
            },
        ),
    ]
